name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook -theme latest
        
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: |
         curl -s https://api.github.com/repos/zjp-CN/mdbook-theme/releases/latest \
              | grep browser_download_url \
              | grep mdbook-theme_linux \
              | cut -d '"' -f 4 \
              | wget -qi -
         tar -xvzf mdbook-theme_linux.tar.gz
         echo $PWD >> $GITHUB_PATH    

      - run: |
          mdbook build
          cp ./config/CNAME ./book/CNAME
          cp ./its_theme/fonts/BF_Modernista.woff ./book/its-theme/fonts/BF_Modernista.woff
          #quick fix to enable BF_Modernista on Brave
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message  }}


      # Broken link checker 
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.1
        with:
          # Required:
          url: 'https://book.interstellar.gg'
          # optional:
          honorRobotExclusions: false
          ignorePatterns: 'github,google'
          recursiveLinks: false # set true later to check all URLs on all reachable pages (could take a while)
          
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"



